In [1]:
import numpy as np

### Creating a 1 dimensional array

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a = np.array([1.1, 2, "sunny", True])

In [5]:
a

array(['1.1', '2', 'sunny', 'True'], dtype='<U32')

### We can see that everything have been converted to an array of string (U32)

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(4,)

In [8]:
# number of dimensions
a.ndim

1

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

### Why numpy operations like array is more efficient than python lists?
##### Memory-efficient container that provides fast numerical operations

Read:
Numpy arrays are specialized data structures. This means we not only get the benefits of an efficient in-memory representation, but efficient specialized implementations as well.

E.g. if you are summing up two arrays the addition will be performed with the specialized CPU vector operations, instead of calling the python implementation of int addition in a loop.

In [10]:
range_1000 = range(1000)
%timeit [i**2 for i in range_1000]

294 µs ± 33.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
range_np_1000 = np.arange(1000)
%timeit range_np_1000 ** 2

932 ns ± 23.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 2 dimensional array

In [12]:
two_d_array = np.array([[1,2,3], [4,5,6]])

In [13]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
type(two_d_array)

numpy.ndarray

In [15]:
# 2 rows and 2 columns
two_d_array.shape

(2, 3)

In [16]:
two_d_array.ndim

2

In [17]:
# returns the size of the first dimension
len(two_d_array)

2

### 3 dimensional array

In [18]:
three_d_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [19]:
three_d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
# 2 rows, 2 columns and depth of 2
three_d_array.shape

(2, 2, 2)

In [21]:
three_d_array.ndim

3

### Multi-dimensional array

In [77]:
multi_d_array = np.array([1,2,3,4], ndmin=5)

In [78]:
multi_d_array

array([[[[[1, 2, 3, 4]]]]])

In [79]:
multi_d_array.shape

(1, 1, 1, 1, 4)

In [80]:
multi_d_array.ndim

5

### Functions for creating array

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# start, end, step size
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [24]:
# linear space start, end, number of points
# bascially divide 0, 1 in 6 points
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
ones_ = np.ones([4,4])

In [32]:
ones_

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
ones_.ndim

2

In [35]:
zeros_ = np.zeros([4,4])

In [36]:
zeros_

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
zeros_.ndim

2

##### Returns 1 in the diagonal element and 0 else where

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### create a diagonal array with the values on the diagonal elements

In [42]:
diag_ = np.diag([1,2,3,4])

In [43]:
diag_

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [47]:
type(diag_)

numpy.ndarray

### get only the diagonal elements

In [48]:
np.diag(diag_)

array([1, 2, 3, 4])

In [60]:
diag_1 = np.diag([[1,2,3,4], [5,6,7,8]])

In [61]:
diag_1

array([1, 6])

#### Create an array of the given shape and populate it with random sample from a uniform distribution over ``[0, 1)``

In [70]:
random_1 = np.random.rand(4)

In [71]:
random_1

array([0.89353184, 0.80585005, 0.04819475, 0.57117375])

#### Create an array of the given shape and populate it with random sample from a standard normal distribution over ``[0, 1)``

In [72]:
random_2 = np.random.randn(4)

In [73]:
random_2

array([-0.66736727, -0.12021662,  1.52252692,  0.25931604])

### Datatypes
Sometimes arrays are displayed with a dot (.) say 2. instead of 2 because of the difference in the datatype

In [82]:
arr1 = np.arange(5)

In [83]:
arr1

array([0, 1, 2, 3, 4])

In [84]:
arr1.dtype

dtype('int64')

In [86]:
type(arr1)

numpy.ndarray

### explicit setting of datatypes

In [89]:
arr2 = np.arange(5, dtype='float')

In [90]:
arr2

array([0., 1., 2., 3., 4.])

In [91]:
arr2.dtype

dtype('float64')

In [95]:
arr3 = np.array([1+2j, 2+3j])

In [96]:
arr3

array([1.+2.j, 2.+3.j])

In [97]:
arr3.dtype

dtype('complex128')

#### Retriving elements from array

In [99]:
arr4 = np.arange(5, dtype='float')

In [100]:
arr4

array([0., 1., 2., 3., 4.])

In [101]:
arr4[1]

1.0

In [103]:
arr4[1:3]

array([1., 2.])

In [106]:
arr5 = np.diag([1,2,3])

In [107]:
arr5

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [109]:
arr5[1]

array([0, 2, 0])

In [110]:
arr5[1,1]

2

In [111]:
arr5[1,1] = 5

In [112]:
arr5

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 3]])

In [127]:
arr6 = np.arange(10)
arr7 = np.arange(5)

In [129]:
arr6[5:] = arr7[::-1]

In [130]:
arr7[::-1]

array([4, 3, 2, 1, 0])

In [131]:
arr6

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

### Copying and views
A slicing operation creates a view on the original array, which is just a way of accessing the array data. 
Thus the original array is not copied in memory. 
We can use np.may_share_memory() to check if 2 arrays share the same memory block.

When modifying the array, the original array is modified array as well.

In [133]:
arr1 = np.arange(10)

In [134]:
arr2 = arr1[::2]

In [138]:
arr2

array([0, 2, 4, 6, 8])

In [137]:
np.may_share_memory(arr1, arr2)

True

#### Internally for memory operation, numpy points to the same memory location but using something called a view

In [139]:
arr2[0] = 10

In [142]:
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [143]:
arr2

array([10,  2,  4,  6,  8])

In [144]:
np.may_share_memory(arr1, arr2)

True

### Force a copy

In [145]:
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [146]:
arr3 = arr1.copy()

In [147]:
arr3

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [150]:
arr3[0] = 15

In [151]:
arr3

array([15,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [152]:
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [153]:
np.may_share_memory(arr1, arr3)

False

#### Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called Fancy indexing. It created copies not views.

In [180]:
arr4 = np.random.randint(0, 5, 10)

In [181]:
arr4

array([1, 3, 0, 2, 3, 2, 4, 1, 2, 2])

In [182]:
mask = (arr4 > 0) & (arr4 % 2 == 0)

In [187]:
mask

array([False, False, False,  True, False,  True,  True, False,  True,
        True])

In [188]:
arr5 = arr4[mask]

In [189]:
arr5

array([2, 2, 4, 2, 2])

In [190]:
np.may_share_memory(arr4, arr5)

False

In [195]:
arr4[[1,2]]

array([3, 0])